{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is a simple API",
    "version" : "1.0.1",
    "title" : "Simple Inventory API",
    "contact" : {
      "email" : "you@your-company.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/ahornung/mockdata/1.0.1",
  "tags" : [ {
    "name" : "admins",
    "description" : "Secured Admin-only calls"
  }, {
    "name" : "developers",
    "description" : "Operations available to regular developers"
  } ],
  "schemes" : [ "https" ],
  "paths" : {
    "/Products" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "searches Products",
        "description" : "By passing in the appropriate options, you can search for\navailable Products in the system\n",
        "operationId" : "searchProducts",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "searchString",
          "in" : "query",
          "description" : "pass an optional search string for looking up Products",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "skip",
          "in" : "query",
          "description" : "number of records to skip for pagination",
          "required" : false,
          "type" : "integer",
          "minimum" : 0,
          "format" : "int32"
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "maximum number of records to return",
          "required" : false,
          "type" : "integer",
          "maximum" : 50,
          "minimum" : 0,
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "search results matching criteria",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/ProductItem"
              }
            }
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      },
      "post" : {
        "tags" : [ "admins" ],
        "summary" : "adds an Products item",
        "description" : "Adds an item to the system",
        "operationId" : "addProduct",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "ProductsItem",
          "description" : "Product item to add",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/ProductItem"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "Products created"
          },
          "400" : {
            "description" : "invalid input, object invalid"
          },
          "409" : {
            "description" : "an existing item already exists"
          }
        }
      }
    }
  },
  "definitions" : {
    "ProductItem" : {
      "type" : "object",
      "required" : [ "Product", "id" ],
      "properties" : {
        "id" : {
          "type" : "string",
          "format" : "uuid",
          "example" : "f290f1ee-6c54-4b01-90e6-d701748f0851"
        },
        "Product" : {
          "$ref" : "#/definitions/Product"
        }
      }
    },
    "Product" : {
      "required" : [ "key" ],
      "properties" : {
        "key" : {
          "type" : "string",
          "example" : "SC"
        },
        "name" : {
          "type" : "string",
          "example" : "SCOM"
        }
      }
    }
  }
}